name: publish

on:
    push:
        branches:
            - "master"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.x
            - run: yarn install
            - run: yarn deploy
              env:
                  KEY: ${{ secrets.PERMAWEB_KEY }}
            - uses: Ilshidur/action-discord@master
              name: Discord Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              with:
                  args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
